spring.application.name=tp1
spring.datasource.url=jdbc:mysql://localhost:3306/tp1?TimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
server.port=8083
